version: 0.2

phases:
  pre_build:
    commands:
    - $(aws ecr get-login --region us-east-2 --no-include-email)
    - REPOSITORY_URI=030304881571.dkr.ecr.us-east-2.amazonaws.com/poc
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
